services:
  app:
    container_name: sk-themed-php8.3
    image: sk-themed-php8.3
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8.3
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./examples/:/var/www/html
    working_dir: /var/www/html